### ISSUE TITLE
Does not work with rack < 2.0.0

### ISSUE THREAD

**Issue by d4be4st** [arkency/image_placeholder#1]
NoMethodError - undefined method `add_header' for #<Rack::Response:0x007fa048c907d0>:

add_header was added in rack 2.0.0 :(

**Comment by bonekost** [comment]
check this PR: https://github.com/arkency/image_placeholder/pull/2
I think it's little hack, but it works for me also with older Rack (1.6.0)
